### ISSUE TITLE
feat: add model generator

### ISSUE THREAD

**Issue by bxcodec** [golangid/goruda#3]
TODO:

- [x] Generate from schema for primitive type (#7)
- [x] Handle that using `$ref` in component (#9)
- [x] Generate from non primitive type(#10)
- [ ] Handle array properly

**Comment by ridhoperdana** [comment]
What do you mean by handle array properly?
From what I see in [this](https://github.com/golangid/goruda/blob/master/generator.go#L98) code, it already been handled correctly @bxcodec
